### ISSUE TITLE
SegFault when imported module is empty

### ISSUE THREAD

**Issue by PH0lder** [munificent/wren#452]
I am learning how to integrate Wren into C and I have code like this:
```
#define DECLARE_FOREIGN_CLASS_FOO       \
"import \"MyMod\" for MyModX, MyModY\n" \
"class Foo {\n"                         \
"  construct new(val) {_val = val}\n"   \
"  foreign static foo(num)\n"           \
"  callFoo() {Foo.foo(_val)}\n"         \
"}\n"
```

When I use that with:
```
WrenInterpretResult result1 = wrenInterpret(vm, DECLARE_FOREIGN_CLASS_FOO);
```

I get this output:
```
Attempting to load module: MyMod
Segmentation fault (core dumped)
```

The loading of the module is controlled by this code:
```
#define MY_MODULE \
" "

char* wrenLoadModuleFn(WrenVM* vm, const char* name)
{
  if (strcmp("MyMod", name) == 0)
  {
    fprintf(stdout, "Attempting to load module: %s\n", name);
    return MY_MODULE;
  }

  fprintf(stderr, "couldn't find module to load: %s\n", name);
  return NULL;
}
```

I ran it in GDB and here's the result:

```
Attempting to load module: MyMod

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff777c0e4 in free () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff777c0e4 in free () from /lib64/libc.so.6
#1  0x00000000004015f9 in defaultReallocate ()
#2  0x00000000004037ff in wrenImportModule ()
#3  0x0000000000412ebf in prim_system_importModule ()
#4  0x0000000000402aa6 in runInterpreter ()
#5  0x00000000004014b4 in main ()
```

Now I do realize that returning an empty module is not a realistic use case, except when learning/debugging, as I am currently doing, but it still looks like a real issue needing fixing to me.

**Comment by PH0lder** [comment]
I figured out how to do the debug version, so here's something a little more useful from the backtrace:

```
Attempting to load module: MyMod

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff777c0e4 in free () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff777c0e4 in free () from /lib64/libc.so.6
#1  0x00000000004019c9 in defaultReallocate (ptr=0x41af3f, newSize=0) at src/vm/wren_vm.c:31
#2  0x0000000000401f25 in wrenReallocate (vm=0x628010, memory=0x41af3f, oldSize=0, newSize=0)
    at src/vm/wren_vm.c:218
#3  0x0000000000405314 in wrenImportModule (vm=0x628010, name=18445618173809242512)
    at src/vm/wren_vm.c:1384
#4  0x0000000000412eaa in prim_system_importModule (vm=0x628010, args=0x639190) at src/vm/wren_core.c:1079
#5  0x0000000000403600 in runInterpreter (vm=0x628010, fiber=0x63ddf0) at src/vm/wren_vm.c:916
#6  0x0000000000405198 in wrenInterpretInModule (vm=0x628010, module=0x41b644 "main", 
    source=0x41af70 "import \"MyMod\" for MyModX, MyModY\nclass Foo {\n  construct new(val) {_val = val}\n  foreign static foo(num)\n  callFoo() {Foo.foo(_val)}\n}\n") at src/vm/wren_vm.c:1340
#7  0x00000000004050d2 in wrenInterpret (vm=0x628010, 
    source=0x41af70 "import \"MyMod\" for MyModX, MyModY\nclass Foo {\n  construct new(val) {_val = val}\n  foreign static foo(num)\n  callFoo() {Foo.foo(_val)}\n}\n") at src/vm/wren_vm.c:1315
#8  0x00000000004015a4 in main ()
```

**Comment by PH0lder** [comment]
Okay, so apparently it's my bad, sort of.  I fixed this issue by using strdup:

```
char* wrenLoadModuleFn(WrenVM* vm, const char* name)
{
  if (strcmp("MyMod", name) == 0)
  {
    fprintf(stdout, "Attempting to load module: %s\n", name);
    return strdup(MY_MODULE);
  }

  fprintf(stderr, "couldn't find module to load: %s\n", name);
  return NULL;
}
```

after having found this comment:

```
  // Modules loaded by the host are expected to be dynamically allocated with
  // ownership given to the VM, which will free it. The built in optional
  // modules are constant strings which don't need to be freed.
```
